// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLXCMfrCsluc1RyqiYOggJeTVD7ufSm7o',
    appId: '1:511212509237:web:2255c91a5c14c66981b97c',
    messagingSenderId: '511212509237',
    projectId: 'bdcalling-65984',
    authDomain: 'bdcalling-65984.firebaseapp.com',
    databaseURL: 'https://bdcalling-65984-default-rtdb.firebaseio.com',
    storageBucket: 'bdcalling-65984.appspot.com',
    measurementId: 'G-C6FF8JC2KE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7Nen7K8wSca9KBq8oyVYyO_Ya9XJ6dUw',
    appId: '1:511212509237:android:43e307de781acdd281b97c',
    messagingSenderId: '511212509237',
    projectId: 'bdcalling-65984',
    databaseURL: 'https://bdcalling-65984-default-rtdb.firebaseio.com',
    storageBucket: 'bdcalling-65984.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZzswS-2HM5DEtdaRL459kfEHKm8_ZvLg',
    appId: '1:511212509237:ios:ce8bb6808803985481b97c',
    messagingSenderId: '511212509237',
    projectId: 'bdcalling-65984',
    databaseURL: 'https://bdcalling-65984-default-rtdb.firebaseio.com',
    storageBucket: 'bdcalling-65984.appspot.com',
    iosBundleId: 'com.example.taskManager',
  );
}
